import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@smastrom/react-rating/style.css";

import BaseLayout from "@/components/Layout/BaseLayout";
import ErrorBoundary from "@/components/ErrorBoundary";
import SessionContext from "@/context/SessionContext";
import { SidebarContextProvider } from "@/context/sidebar-context";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin="anonymous"
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Cinzel&display=swap"
          rel="stylesheet"
        />
        <link href="https://fonts.cdnfonts.com/css/archer-2" rel="stylesheet" />
        <link
          href="https://db.onlinewebfonts.com/c/5346a0951717ff8ed8e9e0253f884d72?family=Cera+Stencil+PRO"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <SessionContext>
          {/* <ErrorBoundary> */}
          <BaseLayout>{children}</BaseLayout>
          {/* </ErrorBoundary> */}
        </SessionContext>
      </body>
    </html>
  );
}
